"""add votes model_source and openrouter_models

Revision ID: 4eaabc31cf4c
Revises: 4f6f46dd6a96
Create Date: 2026-05-24 15:43:17.620468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4eaabc31cf4c'
down_revision: Union[str, Sequence[str], None] = '4f6f46dd6a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openrouter_models',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('context_length', sa.Integer(), nullable=True),
    sa.Column('pricing_prompt', sa.Numeric(), nullable=True),
    sa.Column('pricing_completion', sa.Numeric(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_openrouter_models_is_free'), 'openrouter_models', ['is_free'], unique=False)
    op.add_column('words', sa.Column('model_source', sa.String(length=128), nullable=True))
    op.add_column('words', sa.Column('up_vote', sa.Integer(), server_default='0', nullable=False))
    op.add_column('words', sa.Column('down_vote', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('words', 'down_vote')
    op.drop_column('words', 'up_vote')
    op.drop_column('words', 'model_source')
    op.drop_index(op.f('ix_openrouter_models_is_free'), table_name='openrouter_models')
    op.drop_table('openrouter_models')
    # ### end Alembic commands ###
