"""word_votes table and drop integer counters

Revision ID: 76fb625e49ae
Revises: c98963b230da
Create Date: 2026-05-24 23:12:21.010396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fb625e49ae'
down_revision: Union[str, Sequence[str], None] = 'c98963b230da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word_id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(length=320), nullable=False),
    sa.Column('direction', sa.String(length=4), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction IN ('up', 'down')", name='ck_word_votes_direction'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_id', 'user_email', name='uq_word_votes_word_user')
    )
    op.create_index(op.f('ix_word_votes_word_id'), 'word_votes', ['word_id'], unique=False)
    # NOTE: uq_words_lower_text is a functional unique index on LOWER(text) created in
    # migration c98963b230da. Autogenerate doesn't see expression indexes, so it
    # incorrectly suggests dropping it here — we do NOT drop it.
    op.drop_column('words', 'up_vote')
    op.drop_column('words', 'down_vote')


def downgrade() -> None:
    """Downgrade schema."""
    op.add_column('words', sa.Column('down_vote', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('words', sa.Column('up_vote', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_word_votes_word_id'), table_name='word_votes')
    op.drop_table('word_votes')
