"""vdict_words seed dictionary table

Revision ID: da6af16b2716
Revises: 76fb625e49ae
Create Date: 2026-05-25 16:20:34.515805

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "da6af16b2716"
down_revision: Union[str, Sequence[str], None] = "76fb625e49ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vdict_words",
        sa.Column("vdict_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=512), nullable=False),
        sa.Column("ipa", sa.String(length=256), nullable=True),
        sa.Column("word_type", sa.String(length=64), nullable=True),
        sa.Column(
            "meanings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "friendly",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "examples",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("raw_html", sa.Text(), nullable=True),
        sa.Column(
            "crawled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("vdict_id"),
    )
    op.create_index(op.f("ix_vdict_words_text"), "vdict_words", ["text"], unique=False)
    # Functional index for case-insensitive lookups by headword
    op.create_index(
        "ix_vdict_words_lower_text",
        "vdict_words",
        [sa.text("LOWER(text)")],
        unique=False,
    )
    # NOTE: autogenerate falsely flags uq_words_lower_text (a functional index on
    # LOWER(text) in the words table from migration c98963b230da) for removal.
    # That index is correct and must be preserved — we do NOT drop it here.


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("ix_vdict_words_lower_text", table_name="vdict_words")
    op.drop_index(op.f("ix_vdict_words_text"), table_name="vdict_words")
    op.drop_table("vdict_words")
