"""drop openrouter_models table

Revision ID: dd624386b50f
Revises: 4eaabc31cf4c
Create Date: 2026-05-24 16:26:33.697688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd624386b50f'
down_revision: Union[str, Sequence[str], None] = '4eaabc31cf4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_openrouter_models_is_free'), table_name='openrouter_models')
    op.drop_table('openrouter_models')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openrouter_models',
    sa.Column('id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('context_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pricing_prompt', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('pricing_completion', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('is_free', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('synced_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('openrouter_models_pkey'))
    )
    op.create_index(op.f('ix_openrouter_models_is_free'), 'openrouter_models', ['is_free'], unique=False)
    # ### end Alembic commands ###
