{{- if and .Values.backend.enabled .Values.backend.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "vvn-ce.fullname" . }}-backend
  labels:
    {{- include "vvn-ce.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with .Values.backend.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.backend.ingress.className }}
  ingressClassName: {{ .Values.backend.ingress.className }}
  {{- end }}
  {{- with .Values.backend.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.backend.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "vvn-ce.fullname" . }}-backend
                port:
                  name: http
{{- end }}
